services:

  homelogger:
    image: francislaboratories/homelogger:latest
    volumes:
      - ./server/data:/root/data
    ports:
      - "3005:80"
    environment:
      - DB_DIALECT=sqlite
    restart: unless-stopped
