services:

  homelogger:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../server/data:/root/data
    environment:
      - DB_DIALECT=sqlite
    ports:
      - "3005:3005"
    restart: unless-stopped
 
