services:

  homelogger:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - homelogger-data:/root/data
    environment:
      - DB_DIALECT=sqlite
      - ../server/data:/root/data
    ports:
      - "3005:80"
    restart: unless-stopped

volumes:
  homelogger-data:
 
